default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: root
  password:
  host: <%= ENV.fetch("DATABASE_HOST") { '127.0.0.1' } %>
  database: todolist_backend_development

test:
  <<: *default
  username: root
  password:
  host: <%= ENV.fetch("DATABASE_HOST") { '127.0.0.1' } %>
  database: todolist_backend_test

